#!/usr/bin/env sh

#
#   Copyright 2015 the original author or authors.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        https://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not comply, but you have some other compatible shell such as bash or ksh,
#       then to run this script, type that shell name before the whole command
#       line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#pattern}», «${var%pattern}»
#         * compound commands having a testable exit status, especially «case»
#         * various built-in commands including «command», «set», and «ulimit»
#
#   Important for patching:
#
#   (1) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#

set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "$0" )" && pwd -P )
APP_HOME=$( cd -- "$SCRIPT_DIR/.." && pwd -P )
APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"
WRAPPER_PROPERTIES="$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.properties"
GRADLE_VERSION="8.8"
GRADLE_HOME="$APP_HOME/.gradle-$GRADLE_VERSION"
GRADLE_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"

symlink_resolve() {
    # shellcheck disable=SC2010
    ls -l "$1" 2>/dev/null | grep ' -> ' | sed 's/.*-> \(.*\)/\1/'
}

while IFS="=" read -r key value
do
  case "$key" in
    distributionUrl) GRADLE_URL="$value"
      ;;
  esac
done < "$WRAPPER_PROPERTIES"

echo "Downloading Gradle $GRADLE_VERSION from $GRADLE_URL"
GRADLE_ZIP="/tmp/gradle-$GRADLE_VERSION-bin.zip"

if [ ! -f "$GRADLE_ZIP" ]; then
    curl -L "$GRADLE_URL" -o "$GRADLE_ZIP"
fi

GRADLE_HOME="$APP_HOME/.gradle-$GRADLE_VERSION"
if [ ! -d "$GRADLE_HOME" ]; then
    mkdir -p "$GRADLE_HOME"
    unzip -q "$GRADLE_ZIP" -d "$GRADLE_HOME"
    GRADLE_DIST=$(ls -d "$GRADLE_HOME"/gradle-* | head -1)
    export GRADLE_HOME="$GRADLE_DIST"
else
    GRADLE_DIST=$(ls -d "$GRADLE_HOME"/gradle-* 2>/dev/null | head -1)
    if [ -z "$GRADLE_DIST" ]; then
        echo "Gradle not found in $GRADLE_HOME"
        unzip -q "$GRADLE_ZIP" -d "$GRADLE_HOME"
        GRADLE_DIST=$(ls -d "$GRADLE_HOME"/gradle-* | head -1)
    fi
    export GRADLE_HOME="$GRADLE_DIST"
fi

exec "$GRADLE_HOME/bin/gradle" "$@"
