package dev.msf.core;

import dev.msf.core.compression.CompressionType;
import dev.msf.core.io.MsfReader;
import dev.msf.core.io.MsfReaderConfig;
import dev.msf.core.model.MsfFile;
import dev.msf.core.model.MsfHeader;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests that read known-good and known-bad reference binary files from test
 * resources.
 *
 * <p>
 * Reference files are generated by {@link MsfReferenceFileGenerator}. These
 * tests
 * are only active when the reference files are present on the classpath. On
 * first build,
 * run {@link MsfReferenceFileGenerator} to populate the files.
 *
 * @see MsfReferenceFileGenerator
 */
class MsfReferenceFileTest {

    private static byte[] readResource(String name) throws Exception {
        InputStream is = MsfReferenceFileTest.class.getClassLoader()
                .getResourceAsStream(name);
        if (is == null)
            return null;
        try (is) {
            return is.readAllBytes();
        }
    }

    @SuppressWarnings("unused") // Used by JUnit @EnabledIf annotation
    private static boolean referenceFilesExist() {
        return MsfReferenceFileTest.class.getClassLoader()
                .getResource("known_good_v1_0.msf") != null;
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void knownGoodFile_parsesSuccessfully() throws Exception {
        byte[] bytes = readResource("known_good_v1_0.msf");
        assertNotNull(bytes, "known_good_v1_0.msf must be present in test resources");

        MsfHeader header = MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(1, header.majorVersion());
        assertEquals(0, header.minorVersion());
        assertEquals(3953L, header.mcDataVersion());
        assertEquals(56L, header.fileSize());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void corruptHeaderChecksum_throwsMsfChecksumException() throws Exception {
        byte[] bytes = readResource("corrupt_header_checksum.msf");
        assertNotNull(bytes);

        assertThrows(MsfChecksumException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null));
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void corruptFileChecksum_emitsWarningThenThrows() throws Exception {
        byte[] bytes = readResource("corrupt_file_checksum.msf");
        assertNotNull(bytes);

        List<MsfWarning> warnings = new ArrayList<>();
        assertThrows(MsfChecksumException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, warnings::add));

        assertTrue(
                warnings.stream().anyMatch(w -> w.code() == MsfWarning.Code.FILE_CHECKSUM_FAILURE));
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void unsupportedMajorVersion_throwsMsfVersionException() throws Exception {
        byte[] bytes = readResource("unsupported_major_version.msf");
        assertNotNull(bytes);

        MsfVersionException ex = assertThrows(MsfVersionException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null));
        assertEquals(2, ex.getFoundVersion());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void futureMinorVersion_acceptedByReader() throws Exception {
        byte[] bytes = readResource("future_minor_version.msf");
        assertNotNull(bytes);

        MsfHeader header = MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(1, header.majorVersion());
        assertEquals(7, header.minorVersion());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void fileSizeMismatch_emitsWarning() throws Exception {
        byte[] bytes = readResource("file_size_mismatch.msf");
        assertNotNull(bytes);

        List<MsfWarning> warnings = new ArrayList<>();
        // May also fail checksum — use allowChecksumFailure to focus on size mismatch
        // warning
        MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.allowChecksumFailure(), warnings::add);

        assertTrue(
                warnings.stream().anyMatch(w -> w.code() == MsfWarning.Code.FILE_SIZE_MISMATCH),
                "FILE_SIZE_MISMATCH warning expected");
    }

    // =========================================================================
    // Canonical format vectors (Epic 2)
    // =========================================================================

    @SuppressWarnings("unused")
    private static boolean canonicalVectorsExist() {
        return MsfReferenceFileTest.class.getClassLoader().getResource("minimal.msf") != null;
    }

    @Test
    @EnabledIf("canonicalVectorsExist")
    void minimal_parsesSuccessfully_noCompression() throws Exception {
        byte[] bytes = readResource("minimal.msf");
        assertNotNull(bytes, "minimal.msf must be present");
        MsfFile file = MsfReader.readFile(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(1, file.header().majorVersion());
        assertEquals(1, file.layerIndex().layers().size());
        assertEquals(1, file.layerIndex().layers().get(0).regions().size());
        // Region must use NONE compression
        assertEquals(CompressionType.NONE,
            file.layerIndex().layers().get(0).regions().get(0).compressionType());
        assertTrue(file.entities().isEmpty(), "minimal.msf must have no entity block");
        assertTrue(file.blockEntities().isEmpty(), "minimal.msf must have no block entity block");
    }

    @Test
    @EnabledIf("canonicalVectorsExist")
    void zstd_parsesSuccessfully() throws Exception {
        byte[] bytes = readResource("zstd.msf");
        assertNotNull(bytes, "zstd.msf must be present");
        MsfFile file = MsfReader.readFile(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(CompressionType.ZSTD,
            file.layerIndex().layers().get(0).regions().get(0).compressionType());
    }

    @Test
    @EnabledIf("canonicalVectorsExist")
    void lz4_parsesSuccessfully() throws Exception {
        byte[] bytes = readResource("lz4.msf");
        assertNotNull(bytes, "lz4.msf must be present");
        MsfFile file = MsfReader.readFile(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(CompressionType.LZ4,
            file.layerIndex().layers().get(0).regions().get(0).compressionType());
    }

    @Test
    @EnabledIf("canonicalVectorsExist")
    void brotli_parsesSuccessfully() throws Exception {
        byte[] bytes = readResource("brotli.msf");
        assertNotNull(bytes, "brotli.msf must be present");
        MsfFile file = MsfReader.readFile(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(CompressionType.BROTLI,
            file.layerIndex().layers().get(0).regions().get(0).compressionType());
    }

    @Test
    @EnabledIf("canonicalVectorsExist")
    void entities_parsesSuccessfully_featureFlagsSet() throws Exception {
        byte[] bytes = readResource("entities.msf");
        assertNotNull(bytes, "entities.msf must be present");
        MsfFile file = MsfReader.readFile(bytes, MsfReaderConfig.DEFAULT, null);
        assertTrue(file.header().hasEntities(), "entities.msf must have feature flag bit 0 set");
        assertTrue(file.header().hasBlockEntities(), "entities.msf must have feature flag bit 1 set");
        assertTrue(file.entities().isPresent() && !file.entities().get().isEmpty(),
            "entities.msf must have at least one entity");
        assertTrue(file.blockEntities().isPresent() && !file.blockEntities().get().isEmpty(),
            "entities.msf must have at least one block entity");
        assertEquals("minecraft:armor_stand", file.entities().get().get(0).entityType());
        assertEquals("minecraft:chest", file.blockEntities().get().get(0).blockEntityType());
    }
}
