package dev.msf.core;

import dev.msf.core.io.MsfReader;
import dev.msf.core.io.MsfReaderConfig;
import dev.msf.core.model.MsfHeader;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests that read known-good and known-bad reference binary files from test
 * resources.
 *
 * <p>
 * Reference files are generated by {@link MsfReferenceFileGenerator}. These
 * tests
 * are only active when the reference files are present on the classpath. On
 * first build,
 * run {@link MsfReferenceFileGenerator} to populate the files.
 *
 * @see MsfReferenceFileGenerator
 */
class MsfReferenceFileTest {

    private static byte[] readResource(String name) throws Exception {
        InputStream is = MsfReferenceFileTest.class.getClassLoader()
                .getResourceAsStream(name);
        if (is == null)
            return null;
        try (is) {
            return is.readAllBytes();
        }
    }

    @SuppressWarnings("unused") // Used by JUnit @EnabledIf annotation
    private static boolean referenceFilesExist() {
        return MsfReferenceFileTest.class.getClassLoader()
                .getResource("known_good_v1_0.msf") != null;
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void knownGoodFile_parsesSuccessfully() throws Exception {
        byte[] bytes = readResource("known_good_v1_0.msf");
        assertNotNull(bytes, "known_good_v1_0.msf must be present in test resources");

        MsfHeader header = MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(1, header.majorVersion());
        assertEquals(0, header.minorVersion());
        assertEquals(3953L, header.mcDataVersion());
        assertEquals(56L, header.fileSize());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void corruptHeaderChecksum_throwsMsfChecksumException() throws Exception {
        byte[] bytes = readResource("corrupt_header_checksum.msf");
        assertNotNull(bytes);

        assertThrows(MsfChecksumException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null));
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void corruptFileChecksum_emitsWarningThenThrows() throws Exception {
        byte[] bytes = readResource("corrupt_file_checksum.msf");
        assertNotNull(bytes);

        List<MsfWarning> warnings = new ArrayList<>();
        assertThrows(MsfChecksumException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, warnings::add));

        assertTrue(
                warnings.stream().anyMatch(w -> w.code() == MsfWarning.Code.FILE_CHECKSUM_FAILURE));
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void unsupportedMajorVersion_throwsMsfVersionException() throws Exception {
        byte[] bytes = readResource("unsupported_major_version.msf");
        assertNotNull(bytes);

        MsfVersionException ex = assertThrows(MsfVersionException.class,
                () -> MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null));
        assertEquals(2, ex.getFoundVersion());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void futureMinorVersion_acceptedByReader() throws Exception {
        byte[] bytes = readResource("future_minor_version.msf");
        assertNotNull(bytes);

        MsfHeader header = MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.DEFAULT, null);
        assertEquals(1, header.majorVersion());
        assertEquals(7, header.minorVersion());
    }

    @Test
    @EnabledIf("referenceFilesExist")
    void fileSizeMismatch_emitsWarning() throws Exception {
        byte[] bytes = readResource("file_size_mismatch.msf");
        assertNotNull(bytes);

        List<MsfWarning> warnings = new ArrayList<>();
        // May also fail checksum — use allowChecksumFailure to focus on size mismatch
        // warning
        MsfReader.readHeaderFromBytes(bytes, MsfReaderConfig.allowChecksumFailure(), warnings::add);

        assertTrue(
                warnings.stream().anyMatch(w -> w.code() == MsfWarning.Code.FILE_SIZE_MISMATCH),
                "FILE_SIZE_MISMATCH warning expected");
    }
}
